# Generated by Django 4.1.5 on 2023-09-23 15:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0002_userlesson_last_viewed_at_alter_productuser_access_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productuser',
            name='access',
        ),
        migrations.AlterField(
            model_name='productuser',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец продукта'),
        ),
    ]
