# Generated by Django 4.1.5 on 2023-09-24 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_productuser_access_alter_productuser_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons', to='products.product', verbose_name='Продукт'),
        ),
        migrations.AlterField(
            model_name='productuser',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_user', to='products.product', verbose_name='Продукт'),
        ),
    ]
