# Generated by Django 4.1.5 on 2023-09-24 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_lesson_product_alter_productuser_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userlesson',
            options={'ordering': ['id'], 'verbose_name': 'урок пользователя', 'verbose_name_plural': 'уроки пользователей'},
        ),
    ]
